clinic/controllers/EmployeesController.php
<?php

namespace clinic\controllers;
use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\Url;
use common\models\Employee;
use common\models\Clinic;
use common\models\Office;
use common\models\User;

class EmployeesController extends \yii\web\Controller
{
    public function actionIndex()
    {
		
		$list_clinic = Clinic::find()->where(['user_id'=>Yii::$app->user->identity->id])->all();
		foreach($list_clinic as $li){
			$list_office = Office::find()->where(['clinic_id'=>$li['id']])->all();
		}
		//var_dump($list_office);die();
		foreach($list_office as $l){
			$data = Employee::find()->where(['office_id'=>$l['id']])->all();
		}
		//$data = Employee::find()->all();
		$count_data = Employee::find()->count();
		//$office = \common\models\Office::find()->all();
        return $this->render('index',[
			'data' => $data ,
			'count_data' => $count_data ,
			'office' => $list_office
		]);
        //return $this->redirect(['list-employees']);
    }

    public function actionListEmployees()
    {
		$data = Employee::find()->all();
		$count_data = Employee::find()->count();
		$office = \common\models\Office::find()->all();
        return $this->render('list-employees',[
			'data' => $data ,
			'count_data' => $count_data ,
			'office' => $office
		]);
    }
	
	public function actionActivate($id){
		$model = User :: findOne($id);
		$model->status =1;
		$model->save();
		
		if(!$model->save()){
			var_dump($model->errors);
			die();
		}
		Yii::$app->session->setFlash('success', 'Employee has been Activated.');
		return $this->redirect(['employees/index']);
	}

	public function actionUnactivate($id){
		$model = User :: findOne($id);
		$model->status =0;
		$model->save();
		
		if(!$model->save()){
			var_dump($model->errors);
			die();
		}
		Yii::$app->session->setFlash('success', 'Employee not been Activated.');
		return $this->redirect(['employees/index']);
	}
	public function actionTambah()
    {
		$model = new Employee();
		$list_clinic = Clinic::find()->where(['user_id'=>Yii::$app->user->identity->id])->all();
		foreach($list_clinic as $li){
			$office = Office::find()->where(['clinic_id'=>$li['id']])->all();
		}
		//$office = \common\models\Office::find()->all();
        return $this->render('tambah',[
			'office' => $office,
			'model' => $model,
		]);
    }
	public function actionEditform($id)
    {
		$model = Employee::findOne($id);
		$model2 = User::findOne($model['user_id']);
		$office = \common\models\Office::find()->all();
		$id_user = $model2['id'];
		$id_employee = $model['id'];
        return $this->render('edit',[
			'office' => $office,
			'model' => $model,
			'model2' => $model2,
			'id_user' => $id_user,
			'id_employee' => $id_employee,
		]);
    }

	public function actionDaftar(){
		$model = new User();
		$username = Yii::$app->request->post('User');
        $model->username = $username['email'];
        $model->email = $username['email'];
        $model->password_hash = Yii::$app->getSecurity()->generatePasswordHash('initial');
		//var_dump($model->password_hash);die();
        $model->generateAuthKey();
		$model->role_id = 4;
		$model->status=1;
		$model->created_at=11111;
		$model->updated_at=11111;
		$model->save();
		if($model->save()){
		   $modelmember = new Employee();
		   $member = Yii::$app->request->post('Employee');
		   //var_dump($member);die();
		   $modelmember->name = $member['name'];
		   $modelmember->phone = $member['phone'];
		   $modelmember->office_id = $member['office_id'];
		   $modelmember->user_id = $model->getPrimaryKey();
		   $modelmember->save();
		}else{
			var_dump( $model->errors);
		   die();
		}
		Yii::$app->session->setFlash('success', 'Data Pegawai baru berhasil ditambahkan.');
		return $this->redirect(['index']);
	}
	public function actionEdit($id_user,$id_employee){
		$model = User::findOne($id_user);
		$username = Yii::$app->request->post('User');
        $model->username = $username['email'];
        $model->email = $username['email'];
        $model->password_hash = Yii::$app->getSecurity()->generatePasswordHash('initial');
		//var_dump($model->password_hash);die();
        $model->generateAuthKey();
		$model->role_id = 4;
		$model->status=0;
		$model->created_at=11111;
		$model->updated_at=11111;
		$model->save();
		if($model->save()){
		   $modelmember = Employee::findOne($id_employee);
		   $member = Yii::$app->request->post('Employee');
		   //var_dump($member);die();
		   $modelmember->name = $member['name'];
		   $modelmember->phone = $member['phone'];
		   $modelmember->office_id = $member['office_id'];
		   $modelmember->user_id = $model->getPrimaryKey();
		   $modelmember->save();
		}else{
			var_dump( $model->errors);
		   die();
		}
		Yii::$app->session->setFlash('success', 'Data Pegawai baru berhasil diubah.');
		return $this->redirect(['index']);
	}
	public function actionDelete($id_user,$id_employee)
    {
        $this->findModel($id_employee)->delete();
        $this->findModel2($id_user)->delete();
		Yii::$app->getSession()->setFlash('success', '<i class="fa fa-trash"></i> Data Pegawai berhasil di hapus.');
        return $this->redirect(['index']);
    }
	
	protected function findModel($id)
    {
        if (($model = Employee::findOne(['id' => $id])) !== null) {
            return $model;
        } else {
            echo "error";
        }
    }
	protected function findModel2($id)
    {
        if (($model = User::findOne(['id' => $id])) !== null) {
            return $model;
        } else {
            echo "error";
        }
    }
}

clinic/controllers/VouchersController.php
<?php

namespace clinic\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\Url;
use common\models\Voucher;
use common\models\VoucherHasOffice;
use common\models\Office;
use common\models\Clinic;
use common\models\Category;
use common\models\CategoryHasClinic;
use common\models\OrderVoucher;
use yii\web\UploadedFile;
class VouchersController extends \yii\web\Controller
{
    public function actionIndex()
    {	
		$clinic = Clinic::findOne(['user_id'=>Yii::$app->user->identity->id]);
		$office = Office::find()->where(['clinic_id'=>$clinic['id']])->all();
		$id_office = array();
		foreach($office as $o){
			$id_office[] = $o['id'];
		}
		$listOfVoucher = Voucher::find()->where(['clinic_id' => $clinic->id])->all();

		$listOfCategories = [];
		foreach( $clinic->categories as $v ){
			$listOfCategories[$v->id] = $v->name;
		}
        return $this->render('index',[
			'voucher' => $listOfVoucher,
			//'model' => $voucherModel,
			'listOfCategories' => $listOfCategories
		]);
    }

    public function actionListVouchers($id = null)
    {
		//Mendapatkan List Voucher
		$clinic = Clinic::findOne(['user_id'=>Yii::$app->user->identity->id]);
		
		if( is_null($id) ){
			$voucherModel = new Voucher();
		}else{
			$voucherModel = Voucher::findOne($id);
		}

		if( Yii::$app->request->post() ){
			$post = Yii::$app->request->post();
			$voucherModel->load($post);
			$voucherModel->created_date = date('Y-m-d');
			$voucherModel->discount = (($voucherModel->real_price-$voucherModel->voucher_price)/$voucherModel->real_price*100).'';
			$voucherModel->clinic_id = $clinic->id;
			$voucherModel->upload();
			if( $voucherModel->save() ){
				if( isset($post['office']) ){
					foreach( $post['office'] as $k => $v ){
						$voucherHasOffice = new \common\models\VoucherHasOffice();
						$voucherHasOffice->office_id = $v;
						$voucherHasOffice->voucher_id = $voucherModel->id;
						$voucherHasOffice->save();
					}
				}
				$this->redirect('list-vouchers');
			}else{
				var_dump($voucherModel->errors);
				die();
			}

		}

		$office = Office::find()->where(['clinic_id'=>$clinic['id']])->all();
		$id_office = array();
		foreach($office as $o){
			$id_office[] = $o['id'];
		}
		$listOfVoucher = Voucher::find()->where(['clinic_id' => $clinic->id])->all();

		$listOfCategories = [];
		foreach( $clinic->categories as $v ){
			$listOfCategories[$v->id] = $v->name;
		}

        return $this->render('list-vouchers',[
			'detailClinic' => $clinic,
			'voucher' => $listOfVoucher,
			'model' => $voucherModel,
			'listOfCategories' => $listOfCategories
		]);
    }

    public function actionRedeem()
    {
        return $this->render('redeem');
    }
	public function actionTambah()
    {
		$model = new Voucher();
		$clinic = Clinic::findOne(['user_id'=>Yii::$app->user->identity->id]);
		$listOfCategories = [];
		foreach( $clinic->categories as $v ){
			$listOfCategories[$v->id] = $v->name;
		}
        return $this->render('tambah',[
			'model'=>$model,
			'listOfCategories' => $listOfCategories,
			'detailClinic' => $clinic,
		]);
    }
	
	public function actionEditform($id)
    {
		$model = Voucher::findOne($id);
		$clinic = Clinic::findOne(['user_id'=>Yii::$app->user->identity->id]);
		$listOfCategories = [];
		foreach( $clinic->categories as $v ){
			$listOfCategories[$v->id] = $v->name;
		}
        return $this->render('edit',[
			'model'=>$model,
			'listOfCategories' => $listOfCategories,
			'detailClinic' => $clinic,
		]);
    }
	public function actionEditform1($id)
    {
		$model = Voucher::findOne($id);
		$clinic = Clinic::findOne(['user_id'=>Yii::$app->user->identity->id]);
		$listOfCategories = [];
		foreach( $clinic->categories as $v ){
			$listOfCategories[$v->id] = $v->name;
		}
        return $this->render('edit_gambar',[
			'model'=>$model,
			'listOfCategories' => $listOfCategories,
			'detailClinic' => $clinic,
		]);
    }
	
	public function actionSubmit2()
    {
		$model = new Voucher();
		$clinic = Clinic::findOne(['user_id'=>Yii::$app->user->identity->id]);
		if (Yii::$app->request->isPost) {
				if ($model->load(Yii::$app->request->post())) {
					$uploadModel = UploadedFile::getInstance($model, 'image');
					if ($uploadModel) {
						$namaLogo = $uploadModel->baseName;
						if ($uploadModel->extension == "jpg" || $uploadModel->extension == "jpeg" || $uploadModel->extension == "png") {
							$uploadModel->saveAs('../../site/web/voucher_photo/' . $namaLogo . '.' . $uploadModel->extension);
							$model->image = $namaLogo . '.' . $uploadModel->extension;
							$model->created_date = date('Y-m-d');
							$model->discount = (($model->real_price-$model->voucher_price)/$model->real_price*100).'';
							$model->clinic_id = $clinic->id;
							$model->status=0;
						} else {
							return $this->render('index', [
								'model' => $model,
							]);
						}
					}
					
					if ($model->save()) {         
						//var_dump('test');die();
						if( isset($post['office']) ){
							foreach( $post['office'] as $k => $v ){
								$voucherHasOffice = new \common\models\VoucherHasOffice();
								$voucherHasOffice->office_id = $v;
								$voucherHasOffice->voucher_id = $voucherModel->id;
								$voucherHasOffice->save();
							}
						}
						Yii::$app->session->setFlash('success', 'Data Voucher baru berhasil ditambah.');
						return $this->redirect('index');
					} else {                    
						var_dump($model->errors);die();
					}
				}
			} else {
				var_dump($model->errors);die();
			}
		
        return $this->redirect(['tambah']);
    }
	public function actionEdittext($id)
    {
		$model = Voucher::findOne($id);
		$clinic = Clinic::findOne(['user_id'=>Yii::$app->user->identity->id]);
		if (Yii::$app->request->isPost) {
				if ($model->load(Yii::$app->request->post())) {
					$uploadModel = UploadedFile::getInstance($model, 'image');
					if ($uploadModel) {
						$namaLogo = $uploadModel->baseName;
						if ($uploadModel->extension == "jpg" || $uploadModel->extension == "jpeg" || $uploadModel->extension == "png") {
							$uploadModel->saveAs('../../site/web/voucher_photo/' . $namaLogo . '.' . $uploadModel->extension);
							$model->image = $namaLogo . '.' . $uploadModel->extension;
							$model->created_date = date('Y-m-d');
							$model->discount = (($model->real_price-$model->voucher_price)/$model->real_price*100).'';
							$model->clinic_id = $clinic->id;
						} else {
							return $this->render('index', [
								'model' => $model,
							]);
						}
					}
					
					if ($model->save()) {         
						//var_dump('test');die();
						Yii::$app->session->setFlash('success', 'Data Voucher baru berhasil diubah.');
						return $this->redirect('index');
					} else {                    
						var_dump($model->errors);die();
					}
				}
			} else {
				var_dump($model->errors);die();
			}
		
        return $this->redirect(['tambah']);
    }
	/*public function actionSubmit()
    {
		$voucherModel = new Voucher();
		$clinic = Clinic::findOne(['user_id'=>Yii::$app->user->identity->id]);
		if( Yii::$app->request->post() ){
			$post = Yii::$app->request->post();
			$voucherModel->load($post);
			$voucherModel->created_date = date('Y-m-d');
			$voucherModel->discount = (($voucherModel->real_price-$voucherModel->voucher_price)/$voucherModel->real_price*100).'';
			$voucherModel->clinic_id = $clinic->id;
			$voucherModel->upload();
			if( $voucherModel->save() ){
				if( isset($post['office']) ){
					foreach( $post['office'] as $k => $v ){
						$voucherHasOffice = new \common\models\VoucherHasOffice();
						$voucherHasOffice->office_id = $v;
						$voucherHasOffice->voucher_id = $voucherModel->id;
						$voucherHasOffice->save();
					}
				}
				$this->redirect('list-vouchers');
			}else{
				var_dump($voucherModel->errors);
				die();
			}

		}
		Yii::$app->session->setFlash('success', 'Data Voucher baru berhasil ditambah.');
        return $this->redirect(['tambah']);
    }
	*/
	public function actionEdit($id)
    {
		$voucherModel = Voucher::findOne($id);
		$clinic = Clinic::findOne(['user_id'=>Yii::$app->user->identity->id]);
		if( Yii::$app->request->post() ){
			$post = Yii::$app->request->post();
			$voucherModel->load($post);
			$voucherModel->created_date = date('Y-m-d');
			$voucherModel->discount = (($voucherModel->real_price-$voucherModel->voucher_price)/$voucherModel->real_price*100).'';
			$voucherModel->clinic_id = $clinic->id;
			$voucherModel->upload();
			if( $voucherModel->save() ){
				if( isset($post['office']) ){
					foreach( $post['office'] as $k => $v ){
						$voucherHasOffice = new \common\models\VoucherHasOffice();
						$voucherHasOffice->office_id = $v;
						$voucherHasOffice->voucher_id = $id;
						$voucherHasOffice->save();
					}
				}
				$this->redirect('list-vouchers');
			}else{
				var_dump($voucherModel->errors);
				die();
			}

		}
		Yii::$app->session->setFlash('success', 'Data Voucher baru berhasil diubah.');
        return $this->redirect(['index']);
    }
	
	public function actionDelete($id)
    {
        $this->findModel($id)->delete();
		Yii::$app->getSession()->setFlash('success', '<i class="fa fa-trash"></i> Data Voucher berhasil di hapus.');
        return $this->redirect(['index']);
    }
	
	protected function findModel($id)
    {
        if (($model = Voucher::findOne(['id' => $id])) !== null) {
            return $model;
        } else {
            echo "error";
        }
    }
    public function actionValidate($id_voucher){
		$model = OrderVoucher :: findOne($id_voucher);
		$model->status_validate =1;
		$model->validate_date =date("Y-m-d");
		$model->save();
		
		if(!$model->save()){
			var_dump($model->errors);
			die();
		}
		Yii::$app->session->setFlash('success', 'Voucher has been Validated.');
		return $this->redirect(['sales/index']);
	}
}	

clinic/views/employees/edit.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
?>

<div class="voucher-list">
	<div class="container-fluid">
		<section>
			<div class="section-title">
				<div class="section-title__border"></div>
				<div class="section-title__header"><span></span></div>
			</div>
			<div class="row">
				<div class="col-xs-12">
          <div class="box box-info">
            <!-- /.box-header -->
            <?php $form = yii\widgets\ActiveForm::begin([
                'action' => Url::to(['employees/edit','id_user'=>$id_user,'id_employee'=>$id_employee]),
                'method' => 'POST',
				'options' => ['enctype' => 'multipart/form-data'],
			 ]);  ?>
			 <div class="box-body">
				
                <div class="form-group">
                  <label for="namakategori">ID Employee</label>
                  <?= $form->field($model,'id')->textInput([
							'class' => 'form-control',
							'readonly'=>true,
						])->label(false)?>
                </div>
				<div class="form-group">
                  <label for="namakategori">Nama</label>
                  <?= $form->field($model,'name')->textInput([
							'class' => 'form-control'
						])->label(false)?>
                </div>
				<div class="form-group">
                  <label for="namakategori">Phone</label>
                  <?= $form->field($model,'phone')->textInput([
							'class' => 'form-control'
						])->label(false)?>
                </div>
				<div class="form-group">
                  <label for="namakategori">Email</label>
                  <?= $form->field($model2,'email')->textInput([
							'class' => 'form-control'
						])->label(false)?>
                </div>
				<div class="form-group">
					<label class="control-label">Kantor</label>
					<select name="Employee[office_id]" class="form-control" ng-model="form.category_id">
						<?php foreach($office as $o){?>
							<option value="<?=$o['id']?>"><?= $o['name']?> - <?= $o['address']?></option>
						<?php 
							}
						?>
					</select>
				</div>
              </div>
			  <div class="box-footer">
                <button type="submit" class="btn btn-warning"><i class="fa fa-edit"></i> Edit</button>
				  <a href="<?= Url::to(["employees/index"]); ?>" type="submit" class="btn btn-danger"><i class="fa fa-times"></i> Cancel</a>
              </div>

			<?php yii\widgets\ActiveForm::end(); ?>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
			</div>
		</section>
	</div>

clinic/views/employees/index.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
?>

<div class="voucher-list">
	<div class="container-fluid">
		<section>
			<div class="section-title">
				<div class="section-title__border"></div>
				<div class="section-title__header"><span></span></div>
			</div>
			<div class="row">
				<div class="col-xs-12">
          <div class="box box-info">
			<div class="box-body">
				<?php foreach (Yii::$app->session->getAllFlashes() as $key => $message)
							echo '<div class="alert alert-' . $key . ' ">' . $message . '</div>';
					?>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>ID</th>
				  <th>Name</th>
				  <th>Phone</th>
                  <th>Status</th>
                  <th>Kantor</th>
                  <th>Action</th>
                </tr>
                </thead>
                <tbody>
					<?php 
						$i=1;
						foreach($data as $v){
					?>
					<tr>
						<th><?=$i++?></th>
						<th><?=$v['name']?></th>
						<th><?=$v['phone']?></th>
						<th><?php
							$status = \common\models\User::findOne($v['user_id']);
							if($status['status']==0){
								echo '<span class="label label-danger">Not Active</span>';
							}else{
								echo '<span class="label label-success">Active</span>';
							}?></th>
						<th>
							<?php
								$user = \common\models\Office :: findOne($v['office_id']);
								echo $user->address;
							?>
						</th>
						<th>
						   <a href="<?=Url::to(['employees/editform','id'=>$v['id']]);?>" type="button" class="btn active btn-warning"><span class="fa fa-edit"></span> Edit</a>
						   <?php
							$status = \common\models\User::findOne($v['user_id']);
							if($status['status']==0){
						   ?>
						   <a href="<?=Url::to(['employees/activate','id'=>$v['user_id']]);?>" type="button" class="btn active btn-default"><span class="fa fa-check"></span> Activate</a>
						   <?php
							}else{
						   ?>
						   <a href="<?=Url::to(['employees/unactivate','id'=>$v['user_id']]);?>" type="button" class="btn active btn-default"><span class="fa fa-close"></span> UnActivate</a>
						   <?php
							}
						   ?>
						   <a href="<?=Url::to(['employees/delete','id_employee'=>$v['id'],'id_user'=>$v['user_id']]);?>" type="button" class="btn active btn-danger"><span class="fa fa-trash"></span> Delete</a>
						</th>
					</tr>
					<?php
						}
					?>
                </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
			</div>
		</section>
	</div>

clinic/views/employees/list-employees - Copy.php
<?php
/* @var $this yii\web\View */
?>
<h1>voucher/index</h1>

<p>
    You may change the content of this page by modifying
    the file <code><?= __FILE__; ?></code>.
</p>

clinic/views/employees/list-employees.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
?>

<div class="voucher-list">
	<div class="container-fluid">
		<section>
			<div class="section-title">
				<div class="section-title__border"></div>
				<div class="section-title__header"><span></span></div>
			</div>
			<div class="row">
				<div class="col-xs-12">
          <div class="box box-info">
            <!-- /.box-header -->
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>ID</th>
				  <th>Name</th>
				  <th>Phone</th>
                  <th>Status</th>
                  <th>Kantor</th>
                  <th>Action</th>
                </tr>
                </thead>
                <tbody>
					<?php 
						$i=1;
						foreach($data as $v){
					?>
					<tr>
						<th><?=$i++?></th>
						<th><?=$v['name']?></th>
						<th><?=$v['phone']?></th>
						<th><?php
							$status = \common\models\User::findOne($v['id']);
							if($status['status']==0){
								echo '<span class="label label-danger">Active</span>';
							}else{
								echo '<span class="label label-success">Not Active</span>';
							}?></th>
						<th>
							<?php
								$user = \common\models\Office :: findOne($v['office_id']);
								echo $user->name;
							?>
						</th>
						<th>
						   <a href="<?=Url::to(['vouchers/validate','id_voucher'=>$v['id']]);?>" type="button" class="btn active btn-default"><span class="fa fa-check"></span> Validate</a>
						</th>
					</tr>
					<?php
						}
					?>
                </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
			</div>
		</section>
	</div>

clinic/views/employees/list_employees.php
<div class="topbar" ng-controller="EmployeesController">
	<div class="row narrow">
		<div class="col-sm-2">
			<div class="form-group">
				<select class="form-control">
                    <option>Semua Kategori</option>
                    <option>Dentist</option>
                    <option>Orthopedist</option>
                    <option>Pediatrician</option>
                </select>
			</div>
		</div>
		<div class="col-sm-2">
			<div class="form-group">
				<select class="form-control">
                    <option>Semua Status</option>
                    <option>Expired</option>
                    <option>Stok Habis</option>
                    <option>Stok Hampir Habis</option>
                </select>
			</div>
		</div>
		<div class="col-sm-3">
			<div class="form-group">
				<input type="text" name="" placeholder="Pencarian" class="form-control">
			</div>
		</div>
		<div class="col-sm-5">
			<div class="pull-right">
				<div class="btn btn-default">Total : 14</div>&nbsp;&nbsp;
				<button type="button" class="btn btn-primary" onclick="openRight()">Buat Voucher</button>
			</div>
			<div class="clear"></div>
		</div>
	</div>
</div>
<div class="row operation">
    <div class="col-sm-12 left" ng-controller="ListVoucherController">
        <table class="table table-responsive header-table tb-list-voucher">
          	<thead>
	            <tr>
	              	<th>Nama</th>
	              	<th>Kategori</th>
	              	<th class="text-center">Harga Voucher</th>
	              	<th class="text-center">In Stok</th>
	              	<th class="text-center">Expired Date</th>
	              	<th class="text-center">Status</th>
	            </tr>
          	</thead>
        </table>
        <div class="box-box v3 vtable">
            <table class="table table-responsive table-clickable tb-list-voucher">
	          	<tbody>
		            <tr onclick="openRight()">
		              	<td>Nama Nama Nama Nama NamaNamaNamaNama Nama Nama Nama</td>
		              	<td>Kategori</td>
		              	<td class="text-right">Rp. 200.000</td>
		              	<td class="text-center">10</td>
		              	<td class="text-center">20/10/2016</td>
		              	<td>Expired</td>
		            </tr>
	          	</tbody>
	        </table>
        </div>
    </div>
</div>

clinic/views/employees/tambah.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
?>

<div class="voucher-list">
	<div class="container-fluid">
		<section>
			<div class="section-title">
				<div class="section-title__border"></div>
				<div class="section-title__header"><span></span></div>
			</div>
			<div class="row">
				<div class="col-xs-12">
          <div class="box box-info">
            <!-- /.box-header -->
            <?php $form = yii\widgets\ActiveForm::begin([
                'action' => Url::to(['employees/daftar']),
                'method' => 'POST',
				'options' => ['enctype' => 'multipart/form-data'],
			 ]);  ?>
			 <div class="box-body">
                <div class="form-group">
                  <label for="namakategori">Nama</label>
                  <?= $form->field($model,'name')->textInput([
							'class' => 'form-control'
						])->label(false)?>
                </div>
				<div class="form-group">
                  <label for="namakategori">Phone</label>
                  <?= $form->field($model,'phone')->textInput([
							'class' => 'form-control'
						])->label(false)?>
                </div>
				<div class="form-group">
                  <label for="namakategori">Email</label>
                  <input type="text" name="User[email]" class="form-control">
                </div>
				<div class="form-group">
					<label class="control-label">Kantor</label>
					<select name="Employee[office_id]" class="form-control" ng-model="form.category_id">
						<?php foreach($office as $o){?>
							<option value="<?=$o['id']?>"><?= $o['name']?> - <?= $o['address']?></option>
						<?php 
							}
						?>
					</select>
				</div>
              </div>
			  <div class="box-footer">
                <button type="submit" class="btn btn-primary"><i class="fa fa-plus"></i> Tambah</button>
				  <a href="<?= Url::to(["berita/index"]); ?>" type="submit" class="btn btn-danger"><i class="fa fa-times"></i> Cancel</a>
              </div>

			<?php yii\widgets\ActiveForm::end(); ?>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
        <!-- /.col -->
      </div>
			</div>
		</section>
	</div>