site/controllers/LocationController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\web\Controller;
use common\models\Country;
use common\models\City;
use common\models\Province;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;

class LocationController extends Controller{

    public function actionGetCountry(){
        $out = ArrayHelper::map(Country::find()->all(),'id','name');        
        $selected = '';
        foreach( $out as $k => $v ){
            if( strtolower($v) == 'indonesia' ){
                $selected = $k;
                break;
            }
        }

        return Json::encode([
            'output' => $out,
            'selected' => $selected
        ]);
    }

    public function actionGetProvinceByCountry(){
        $out = [];
        $postData = Yii::$app->request->post('depdrop_parents');
        if( isset($postData) ){
            $id = isset($postData[0]) ? $postData[0] : 0;
            $list = Province::find()->where([
                'country_id' => $id
            ])->all();

            foreach($list as $k => $v){
                $out[] = [
                    'id' => $v['id'],
                    'name' => $v['name']
                ];
            }
        }

        return Json::encode([
            'output' => $out,
            'selected' => ''
        ]);
    }

    public function actionGetCityByProvince(){
        $out = [];
        $postData = Yii::$app->request->post('depdrop_parents');
        if( isset($postData) ){
            $id = isset($postData[0]) ? $postData[0] : 0;
            $list = City::find()->where([
                'province_id' => $id
            ])->all();

            foreach($list as $k => $v){
                $out[] = [
                    'id' => $v['id'],
                    'name' => $v['name']
                ];
            }
        }

        return Json::encode([
            'output' => $out,
            'selected' => ''
        ]);
    }

}

site/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\UploadedFile;
use common\models\LoginForm;
use common\models\User;
use common\models\Member;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use yii\data\Pagination;
use common\models\Clinic;
use common\models\Office;
use common\models\UploadForm;
use common\models\Constant;
use common\models\Voucher;
use common\models\OrderVoucher;
use common\models\ListTransaction;

/**
 * Site controller
 */
class SiteController extends Controller
{
	public $successUrl = 'Success';
    /**
     * @inheritdoc
     */
	 
	 
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    //'logout' => ['post'],
                ],
            ],
        ];
    }
	
	public function actions()
    {
        return [
			'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
            'auth' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'successCallback'],
                //'successUrl' => $this->successUrl
            ],
        ];
    }
	
	public function successCallback($client){
		//var_dump('test');die();
		$attributes = $client->getUserAttributes();	
		$client2 = Yii::$app->get('authClientCollection');
		//if($client2->getClient('google') == true){
		  
		if(isset($attributes['emails'])){
		    //var_dump($client2->getClient('google'));die();
	        $email = $attributes['emails'][0]['value'];
		}else{
		    $email = $attributes['email'];
		}
		//var_dump($attributes);die();
		$user = \common\models\User::find()->where(['email'=>$email])->one();
		if(!empty($user)){
			//Yii::$app->user->login($user);
			//var_dump($user['email']);die();
            Yii::$app->user->login($user, 3600 * 24 * 30);
			//Yii::$app->user->login($user);
			//var_dump($user['email']);die();
//			return $this->redirect(\yii\helpers\Url::to(['site/index','user'=>$user->email]));
			//var_dump('masuk');die();
			return $this->redirect(\yii\helpers\Url::to(['site/index']));					
			//var_dump('masuk');die();
			
		}
		else{
			$session = Yii::$app->session;
			$session['attributes']=$attributes;
			$this->successUrl = \yii\helpers\Url::to(['site/daftarsocial']);
			return $this->redirect($this->successUrl);
		}   
		//var_dump('test');die();
	}
	//public $successUrl = 'Success'; 
    public function actionSearchVoucher($q="",$sc=0){
        $listVoucher = \common\models\Voucher::find()
            ->where(['like','name',$q]);

        if( $sc != 0 ){
            $listVoucher = $listVoucher->andWhere(['category_id' => $sc]);
        }
        return $this->render('search-voucher',[
            'listVoucher' => $listVoucher->all()
        ]);
    } 
	public function actionSemuaklinik()
    {
		$model = new LoginForm();
		$category = \common\models\Category::find()->all();
		$clinic = \common\models\Clinic::find()->all();
		$countclinic = \common\models\Clinic::find();
		$pages = new Pagination([ 'defaultPageSize' => 10,'totalCount' => $countclinic->count()]);
		$clinics = $countclinic->offset($pages->offset)
					->limit($pages->limit)
					->all();
        return $this->render('semuaklinik',[
			'model'=>$model,
			'category'=>$category,
			'clinic'=>$clinics,
			'pages' => $pages
		]);
    }
	
	public function actionSemuavoucher()
    {
		$model = new LoginForm();
		$category = \common\models\Category::find()->all();
		$voucher = \common\models\Voucher::find()->all();
		$countvoucher = \common\models\Voucher::find();
		$pages = new Pagination([ 'defaultPageSize' => 8,'totalCount' => $countvoucher->count()]);
		$vouchers = $countvoucher->offset($pages->offset)
					->limit($pages->limit)
					->all();
        return $this->render('semuavoucher',[
			'model'=>$model,
			'category'=>$category,
			'voucher'=>$vouchers,
			'pages' => $pages
		]);
    }
	public function actionSearchkategori($id)
    {
		$category = \common\models\Category::find()->where(['id'=>$id])->all();
		$category_clinic = \common\models\CategoryHasClinic::find()->where(['category_id'=>$id])->all();
		$id_clinic = array();
		foreach($category_clinic as $c){
			$id_clinic[] = $c['clinic_id'];
		}
		$clinic = \common\models\Clinic::find()->where(['id'=>$id_clinic])->all();
		$voucher = \common\models\Voucher::find()->where(['category_id'=>$id])->all();
		//var_dump($clinic);die();
        return $this->render('search_kategori',[
			'category' => $category,
			'clinic' => $clinic,
			'voucher' => $voucher
		]);
    }
    /**
     * @inheritdoc
     */
    

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $listVoucher = Voucher::find()
			->where(['status'=>1])
            ->limit(4)
			->orderBy(['id'=>SORT_DESC])
            ->all(); 
		$category = \common\models\Category::find()->orderBy(['name'=>SORT_ASC])->all();
		$clinic = \common\models\Clinic::find()->orderBy(['id'=>SORT_DESC])->limit(6)->all();
		$model = new LoginForm();
        return $this->render('index',[
			'model'=>$model,
			'category'=>$category,
			'clinic'=>$clinic,
            'listVoucher' => $listVoucher
		]);
    }
    public function actionAboutus()
    {
        $aboutus = \common\models\AboutUs::findOne(1);
        return $this->render('aboutus',[
		    'model'=>$aboutus,
		]);
    }
        public function actionHelp()
    {
        $help = \common\models\Help::findOne(1);
        return $this->render('help',[
		    'model'=>$help
		]);
    }
    public function actionFaq()
    {
        $faq = \common\models\Faq::findOne(1);
        return $this->render('faq',[
		    'model'=>$faq
		]);
    }
    public function actionAturanpenggunaan()
    {
        $aboutus = \common\models\AturanPenggunaan::findOne(1);
        return $this->render('aturanpenggunaan',[
		    'model'=>$aboutus,
		]);
    }
    public function actionKebijakanprivasi()
    {
        $aboutus = \common\models\KebijakanPrivasi::findOne(1);
        return $this->render('kebijakanprivasi',[
		    'model'=>$aboutus,
		]);
    }
	public function actionDetail($id)
    {
        
        $listVoucher = Voucher::findOne($id); 
		$category = \common\models\Category::find()->all();
		$transaction = new OrderVoucher();
		//var_dump($rand);die();
        return $this->render('detailvoucher',[
			'category'=>$category,
            'listVoucher' => $listVoucher,
            'model' => $transaction,
		]);
    }
	public function actionDetailklinik($id)
    {
        $listClinic = Clinic::findOne($id); 
        $category = \common\models\Category::find()->all();      
        $vouchers = \common\models\Voucher::find()
            ->where(['clinic_id' => $id])->all();
        
        return $this->render('detailklinik',[
			'category'=>$category,
            'listClinic' => $listClinic,
            'listVoucher' => $vouchers
		]);
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
		$listVoucher = Voucher::find()
            ->limit(4)
            ->all(); 
			
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
		$category = \common\models\Category::find()->orderBy(['name'=>SORT_ASC])->all();
		$clinic = \common\models\Clinic::find()->orderBy(['id'=>SORT_DESC])->limit(6)->all();
		//var_dump($model);die();
        if ($model->load(Yii::$app->request->post()) && $model->login() && Yii::$app->user->identity->role_id == 5) {
			//var_dump(Yii::$app->user->identity->role_id);die();
            return $this->goBack();
        } else {
            return $this->render('index', [
                'model' => $model,
				'category'=>$category,
				'clinic'=>$clinic,
				'listVoucher' => $listVoucher,
            ]);
        }
    }
	
	public function actionLoginmember()
    {
		$listVoucher = Voucher::find()
            ->limit(4)
            ->all(); 
		
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(\yii\helpers\Url::to(['site/index']));
        }

        $model = new LoginForm();
		//var_dump($model);die();
        if ($model->load(Yii::$app->request->post()) && $model->login() && Yii::$app->user->identity->role_id == 5) {
			//var_dump('test');die();
            return $this->redirect(\yii\helpers\Url::to(['site/index']));
        } else {
			//var_dump($model->errors);die();
			Yii::$app->session->setFlash('danger', 'Gagal Tidak Bisa Login Karena Username atau Password Salah.');
			return $this->redirect(\yii\helpers\Url::to(['site/index']));
            /*return $this->render('index', [
                'model' => $model,
				'listVoucher' => $listVoucher,
            ]);*/
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
   /* public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
	*/
    /**
     * Displays contact page.

site/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>This is the About page. You may modify the following file to customize its content:</p>

    <code><?= __FILE__ ?></code>
</div>

site/views/site/aturanpenggunaan.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use kartik\depdrop\DepDrop;
use common\models\Category;
use common\models\Country;
use common\models\Province;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;

$this->title = 'Aturan Penggunaan';

?>

<div class="contact-top">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <div class="ask">
                    <strong>Ada pertanyaan? </strong>
                    Kami siap membantu Anda.
                </div>
            </div>
            <div class="col-md-6">
                <div class="the-contact">
                    <div class="item">
                        <a href="mailto:ask@berobat.id"><i class="fa fa-envelope"></i> berobatid@gmail.com</a>
                    </div>
                    <div class="item">
                        <a href="tel:0822 3102 3315"><i class="fa fa-phone"></i> 0822 3102 3315</a>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<br>
<div class="become-clinic-partner">
	<section class="about">
		<div class="container">
			<h2>Aturan Penggunaan</h2>
			<?=$model->description?>
		</div>
	</section>
</div>

site/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'subject') ?>

                <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

site/views/site/daftar.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use kartik\date\DatePicker;
use kartik\depdrop\DepDrop;
use common\models\Country;
use common\models\Province;
use yii\helpers\ArrayHelper;

$model = new common\models\Member();
$country = Country::find()->all();

$countries = ArrayHelper::map(
	$country,'id','name'
);
?>
<div class="become-clinic-partner">
	<section class="form-register">
		<div class="container">
			<h2>Register Your Account</h2>
			<?php $form = ActiveForm::begin([
					'action' => Url::to(['site/daftarmembersocial']),
					'method' => 'POST'
			]); ?>
			<div class="form-group">
				<div class="input-group">
					<span class="input-group-addon" id="basic-addon1"><i class="fa fa-user"></i></span>
					<input type="text" name="User[username]" readonly value="<?=$name?>" class="form-control" placeholder="Full Name" aria-describedby="basic-addon1">
				</div>
			</div>
			<div class="form-group">
				<div class="input-group">
					<span class="input-group-addon" id="basic-addon2"><i class="fa fa-envelope"></i></span>
					<input type="email" name="User[email]" readonly value="<?=$email?>" class="form-control" placeholder="Email. Contoh: name@example.com" aria-describedby="basic-addon2">
				</div>
			</div>
			<div class="form-group">
					<div class="input-group">
					  	<span class="input-group-addon" id="basic-addon2"><i class="fa fa-phone"></i></span>
					  	<input type="number" name="User[no_telepon]" class="form-control" placeholder="No Telepon. Contoh: 082232566162" aria-describedby="basic-addon2">
					</div>
				</div>
			<div class="form-group">
				<div class="input-group">
					<span class="input-group-addon" id="basic-addon2"><i class="fa fa-lock"></i></span>
					<input type="password" name="User[password_hash]" required class="form-control" placeholder="Password. Minimal 6 karakter" aria-describedby="basic-addon2">
				</div>
			</div>
			<div class="form-group">
				<div class="radio">
					<?php 
						$code = common\models\Gender::find()->all();
						foreach($code as $data){
							echo '<label><input type="radio" name="Member[gender_id]" id="optionsRadios1" value="'.$data['id'].'" checked>'.$data['value'].'</label>&nbsp;&nbsp;&nbsp;';
						}
					?>
				</div>
			</div>
			<div class="form-group">
			<!--					<div class="input-group"> -->
					<?= $form->field($model, 'birtdate')->widget(DatePicker::classname(), [
								'options' => ['placeholder' => 'Enter birth date ...'],
								'pluginOptions' => [
									'autoclose'=>true,
									'format' => 'yyyy-mm-dd'
								]
							])->label(false);		
					?>
			<!--				  	<span class="input-group-addon" id="basic-addon2"><i class="fa fa-calendar"></i></span>
					<input type="text" id="datepicker" class="form-control" placeholder="Tanggal lahir" aria-describedby="basic-addon2"> -->
			<!--					</div> -->
			</div>
			<div class="form-group">
				<fieldset class="group-address">
					<legend>Address</legend>
					<div class="row">
						<div class="col-sm-12">
							<div class="form-group">
								<?= 								
									Html::dropDownList(null,'',$countries,[
										'id' => 'country-list',
										'class' => 'form-control',
										'prompt'=>'Select Country...'
									]);
								?>
							</div>
						</div>
						<div class="col-sm-12">
							<div class="form-group">
								<?=
									DepDrop::widget([
										'name' => 'province-list',
										'options' => [
											'id' => 'province-list',
											'class' => 'form-control',
										],
										'pluginOptions' => [
											'placeholder' => 'Select Province',
											'url' => Url::to(['location/get-province-by-country']),
											'depends' => ['country-list'],
										]
									])									
								?>
							</div>
						</div>
						<div class="col-sm-12">
							<div class="form-group">
								<?=
									$form->field($model,'city_id')->widget(DepDrop::className(),[
										'pluginOptions' => [
											'placeholder' => 'Select City',
											'url' => Url::to(['location/get-city-by-province']),
											'depends' => ['province-list'],
										]
									])->label(false);
								?>
							</div>
						</div>
					</div>
				</fieldset>
			</div>
			<div class="lr-input__desc">
				Dengan klik Register, kamu telah menyetujui
				<?= Html::a( "Aturan Penggunaan", ['/site/aturanpenggunaan']) ?> dan <?= Html::a( "Kebijakan Privasi", ['/site/kebijakanprivasi']) ?> dari Berobat.id
			</div>
			<div class="form-group">
				<button type="submit" class="btn btn-primary btn-full">Register</button>
			</div>
			<?php ActiveForm::end(); ?>
		</div>
	</section>
</div>

site/views/site/help.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use kartik\depdrop\DepDrop;
use common\models\Category;
use common\models\Country;
use common\models\Province;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;

$this->title = 'Help';


?>

<div class="contact-top">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <div class="ask">
                    <strong>Ada pertanyaan? </strong>
                    Kami siap membantu Anda.
                </div>
            </div>
            <div class="col-md-6">
                <div class="the-contact">
                    <div class="item">
                        <a href="mailto:ask@berobat.id"><i class="fa fa-envelope"></i> berobatid@gmail.com</a>
                    </div>
                    <div class="item">
                        <a href="tel:0822 3102 3315"><i class="fa fa-phone"></i> 0822 3102 3315</a>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<br>
<div class="become-clinic-partner">
	<section class="about">
		<div class="container">
			<h2>Help</h2>
			<?=$model->description?>
		</div>
	</section>
</div>

site/views/site/kebijakanprivasi.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use kartik\depdrop\DepDrop;
use common\models\Category;
use common\models\Country;
use common\models\Province;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;

$this->title = 'Kebijakan Privasi';

?>

<div class="contact-top">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <div class="ask">
                    <strong>Ada pertanyaan? </strong>
                    Kami siap membantu Anda.
                </div>
            </div>
            <div class="col-md-6">
                <div class="the-contact">
                    <div class="item">
                        <a href="mailto:ask@berobat.id"><i class="fa fa-envelope"></i> berobatid@gmail.com</a>
                    </div>
                    <div class="item">
                        <a href="tel:0822 3102 3315"><i class="fa fa-phone"></i> 0822 3102 3315</a>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<br>
<div class="become-clinic-partner">
	<section class="about">
		<div class="container">
			<h2>Kebijakan Privasi</h2>
			<?=$model->description?>
		</div>
	</section>
</div>

site/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>

                <div style="color:#999;margin:1em 0">
                    If you forgot your password you can <?= Html::a('reset it', ['site/request-password-reset']) ?>.
                </div>

                <div class="form-group">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

site/views/site/loginsocial.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use kartik\date\DatePicker;
use kartik\depdrop\DepDrop;
use common\models\Country;
use common\models\Province;
use yii\helpers\ArrayHelper;

$model = new common\models\Member();
$country = Country::find()->all();

$countries = ArrayHelper::map(
	$country,'id','name'
);
?>
<div class="become-clinic-partner">
	<section class="form-register">
		<div class="container">
			<h2>Login to Your Account</h2>
			<?php $form = ActiveForm::begin([
						'action' => Url::to(['site/loginmember']),
						'method' => 'POST'
				]); ?>
				<div class="form-group">
					<div class="input-group">
					  	<span class="input-group-addon" id="basic-addon1"><i class="fa fa-envelope"></i></span>
					  	<input type="text" name="LoginForm[username]" value="<?=$email?>" required readonly class="form-control" placeholder="Email Anda" aria-describedby="basic-addon1">
					</div>
				</div>
				<div class="form-group">
					<div class="input-group">
					  	<span class="input-group-addon" id="basic-addon2"><i class="fa fa-lock"></i></span>
					  	<input type="password" name="LoginForm[password]" required class="form-control" placeholder="Password Anda" aria-describedby="basic-addon2">
					</div>
				</div>
				<div class="lr-input__desc">
					<div class="clear"></div>
				</div>
				<div class="form-group">
					<button type="submit" class="btn btn-primary btn-full">Login</button>
				</div>
				<?php ActiveForm::end(); ?> 
		</div>
	</section>
</div>

site/views/site/order_voucher.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use kartik\date\DatePicker;
use kartik\depdrop\DepDrop;
use common\models\Country;
use common\models\Province;
use yii\helpers\ArrayHelper;

$country = Country::find()->all();

$countries = ArrayHelper::map(
	$country,'id','name'
);
?>
<div class="become-clinic-partner">
	<section class="form-register">
		<div class="container">
			<h2>Order Voucher</h2>
			<?php $form = ActiveForm::begin([
					'action' => Url::to(['site/purchase','id_voucher'=>$listVoucher->id,'id_user'=>Yii::$app->user->identity->id]),
					'method' => 'POST'
			]); ?>
			<div class="form-group">
				<div class="input-group">
					<span class="input-group-addon" id="basic-addon1"><i class="fa fa-shopping-cart"></i></span>
					<input type="text" readonly value="<?=$listVoucher->name?>" class="form-control" placeholder="Full Name" aria-describedby="basic-addon1">
				</div>
			</div>
			<div class="row">
			  <div class="col-sm-12">
				<div class="form-group">
					<?= $form->field($model, 'date_used')->widget(DatePicker::classname(), [
								'options' => ['placeholder' => 'Tanggal Penggunaan ...'],
								'pluginOptions' => [
									'autoclose'=>true,
									'format' => 'yyyy-mm-dd'
								]
							])->label(false);		
					?>
				</div>
			  </div>
			</div>
			<div class="form-group">
				<button type="submit" class="btn btn-primary btn-full">Order</button>
			</div>
			<?php ActiveForm::end(); ?>
		</div>
	</section>
</div>

site/views/site/semuaklinik.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\LinkPager;
$this->title = "Situs Beli Voucher Treatment Kesehatan Online Mudah Dan Terpecaya";
?>

<div id="clinic-list">
	<div class="container-fluid">
		<section>
			<div class="section-title">
				<div class="section-title__border"></div>
				<div class="section-title__header"><span>Klinik Patner</span></div>
			</div>
			<div class="section-action">
				<div class="pull-right">
					<?= Html::a( "Menjadi Klinik Patner Kami", ['/site/become-clinic-partner'], ['class'=>"btn btn-primary btn-sm"]) ?>
					<!--<a class="btn btn-default btn-sm">Lihat Semua</a>-->
				</div>
				<div class="clear"></div>
			</div>
			<div class="row">
				<?php 
					foreach($clinic as $cli){
				?>
				<div class="col-md-2 col-sm-3 col-xs-12">
					<a href="<?=Url::to(['site/detailklinik','id'=>$cli['id']]);?>" class="the-clinic">
						<div class="logo-clinic" style="background-image: url('<?= Yii::$app->request->baseUrl ?>/site/web/uploads/<?= $cli['logo']?>')"></div>
					</a>
				</div>
				<?php }?>
			</div>
			<?php
				echo LinkPager::widget([
					'pagination' => $pages,
				]);
			?>
		</section>
	</div>
</div>