admin/controllers/BeritaController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\Url;
use common\models\Berita;
use yii\web\UploadedFile;

/**
 * Site controller
 */
class BeritaController extends Controller {

    /**
     * @var boolean whether to enable CSRF validation for the actions in this controller.
     * CSRF validation is enabled only when both this property and [[Request::enableCsrfValidation]] are true.
     */
    //public $enableCsrfValidation = false;
    
    public function actionIndex() {
		$this->layout="main";
		$logo = Berita::find()->all();
	    return $this->render('index', [
			'model' => $logo
		]);
    }
	public function actionEditform($id) {
		$logo = Berita::findOne(['id' => $id]);
		return $this->render('edit', [
			'model' => $logo,
		]);
    }
	public function actionEditform1($id) {
		$logo = Berita::findOne(['id' => $id]);
		return $this->render('edit_gambar', [
			'model' => $logo,
		]);
    }
	public function actionCreate() {
		$logo = new Berita();
		return $this->render('create', [
			'model' => $logo,
		]);
    }
	public function actionEdit($id) {
            $model = $this->findModel($id);
			if (Yii::$app->request->isPost) {
				if ($model->load(Yii::$app->request->post())) {
					$uploadModel = UploadedFile::getInstance($model, 'gambar');
					if ($uploadModel) {
						$namaLogo = $uploadModel->baseName;
						if ($uploadModel->extension == "jpg" || $uploadModel->extension == "jpeg" || $uploadModel->extension == "png") {
							$uploadModel->saveAs('../../frontend/web/berita/' . $namaLogo . '.' . $uploadModel->extension);
							$model->gambar = $namaLogo . '.' . $uploadModel->extension;
						} else {
							return $this->render('index', [
								'model' => $model,
							]);
						}
					}
					
					if ($model->save()) {         
						//var_dump('test');die();
						Yii::$app->getSession()->setFlash('success', '<i class="fa fa-edit"></i> Berita berhasil di ubah.');
						return $this->redirect('index');
					} else {                    
						return $this->render('index', [
									'model' => $model,
						]);
					}
				}
			} else {
				return $this->render('create', [
							'model' => $model,
				]);
			}
            if( !$model->save() ){
               var_dump( $model->errors);
               die();
            }
           return $this->redirect(['index']);
    } 
	public function actionEditgambar($id) {
            $model = $this->findModel($id);
			if (Yii::$app->request->isPost) {
				if ($model->load(Yii::$app->request->post())) {
					$uploadModel = UploadedFile::getInstance($model, 'gambar');
					if ($uploadModel) {
						$namaLogo = $uploadModel->baseName;
						if ($uploadModel->extension == "jpg" || $uploadModel->extension == "jpeg" || $uploadModel->extension == "png") {
							$uploadModel->saveAs('../../frontend/web/berita/' . $namaLogo . '.' . $uploadModel->extension);
							$model->gambar = $namaLogo . '.' . $uploadModel->extension;
						} else {
							return $this->render('index', [
								'model' => $model,
							]);
						}
					}
					
					if ($model->save()) {         
						//var_dump('test');die();
						Yii::$app->getSession()->setFlash('success', '<i class="fa fa-edit"></i> Berita berhasil di ubah.');
						return $this->redirect('index');
					} else {                    
						return $this->render('index', [
									'model' => $model,
						]);
					}
				}
			} else {
				return $this->render('create', [
							'model' => $model,
				]);
			}
            if( !$model->save() ){
               var_dump( $model->errors);
               die();
            }
           return $this->redirect(['index']);
    } 
	public function actionSubmit() {
            $model = new Berita();
			$model->date_created = Date("Y-m-d");
			if (Yii::$app->request->isPost) {
				if ($model->load(Yii::$app->request->post())) {
					$uploadModel = UploadedFile::getInstance($model, 'gambar');
					if ($uploadModel) {
						$namaLogo = $uploadModel->baseName;
						if ($uploadModel->extension == "jpg" || $uploadModel->extension == "jpeg" || $uploadModel->extension == "png") {
							$uploadModel->saveAs('../../frontend/web/berita/' . $namaLogo . '.' . $uploadModel->extension);
							$model->gambar = $namaLogo . '.' . $uploadModel->extension;
						} else {
							return $this->render('index', [
								'model' => $model,
							]);
						}
					}
					
					if ($model->save()) {         
						//var_dump('test');die();
						Yii::$app->getSession()->setFlash('success', '<i class="fa fa-save"></i> Berita berhasil di tambahkan.');
						return $this->redirect('index');
					} else {                    
						return $this->render('index', [
									'model' => $model,
						]);
					}
				}
			} else {
				return $this->render('create', [
							'model' => $model,
				]);
			}
            if( !$model->save() ){
               var_dump( $model->errors);
               die();
            }
           return $this->redirect(['index']);
    } 
	public function actionDelete($id)
    {
        $this->findModel($id)->delete();
		Yii::$app->getSession()->setFlash('success', '<i class="fa fa-trash"></i> Berita berhasil di hapus.');
        return $this->redirect(['index']);
    }
	
	protected function findModel($id)
    {
        if (($model = Berita::findOne(['id' => $id])) !== null) {
            return $model;
        } else {
            echo "error";
        }
    }
	
}

admin/controllers/ClinicController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use common\models\Clinic;
use common\models\Employee;
use common\models\ClinicSearch;
use common\models\Constant;
use common\models\Office;
use common\models\Voucher;
use yii\helpers\Url;

/**
 * Site controller
 */
class ClinicController extends Controller
{
    
public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
				'only' => ['index','detail','approve','nonapprove','remove'],
                'rules' => [
                    [
                        'actions' => ['index','detail','approve','nonapprove','remove'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                    'remove' => ['post']
                ],
            ],
        ];
    }    
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new ClinicSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

		$data = Clinic::find()->all();
		return $this->render('index',[
            'search' => $searchModel,
            'provider' => $dataProvider,
			'model' => $data
		]);
    }

    public function actionDetail($id)
    {
		$data = Clinic::findOne($id);

        $searchModel = new \common\models\ClinicSearch();
        $dataProvider = new \yii\data\ActiveDataProvider([
            'query' => \common\models\Voucher::find()->where([
                'clinic_id' => $data->id
            ])
        ]);
		
		$clinic = Clinic::findOne($id);
		$office = Office::find()->where(['clinic_id'=>$clinic['id']])->all();
		$id_office = array();
		foreach($office as $o){
			$id_office[] = $o['id'];
		}
		$listOfVoucher = Voucher::find()->where(['clinic_id' => $clinic->id])->all();
		//var_dump($data);die();
        return $this->render('detail',[
			'data'=>$data,
			'voucher'=>$listOfVoucher,
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel
		]);
    }
	
	public function actionAccept($id_voucher){
		$model = Voucher :: findOne($id_voucher);
		$model->status =1;
		$model->save();
		
		if(!$model->save()){
			var_dump($model->errors);
			die();
		}
		Yii::$app->session->setFlash('success', 'Voucher has been Accepted.');
		return $this->redirect(['clinic/detail','id'=>$model->clinic_id]);
	}
	public function actionNonaccept($id_voucher){
		$model = Voucher :: findOne($id_voucher);
		$model->status =0;
		$model->save();
		
		if(!$model->save()){
			var_dump($model->errors);
			die();
		}
		Yii::$app->session->setFlash('success', 'Voucher has been Accepted.');
		return $this->redirect(['clinic/detail','id'=>$model->clinic_id]);
	}
	public function actionAddemployee($id)
    {
		$model = new \common\models\Employee();
		$office = \common\models\Office::find()->where(['clinic_id'=>$id])->all();
        return $this->render('addemployee',[
			'model'=>$model,
			'id' =>$id,
			'office'=>$office,
		]);
    }
	public function actionUbahemployee($id)
    {
		$model = \common\models\Employee::findOne($id);
		$id_user = $model->user_id;
		$office = \common\models\Office::findOne($model->office_id);
		$clinic = \common\models\Clinic::find()->where(['id'=>$office->clinic_id])->all();
		foreach($clinic as $c){
			$id_clinic = $c->id;
		}
		//var_dump($office);die();
		$model2 = \common\models\User::findOne($id_user);		
		$listoffice = \common\models\Office::find()->where(['clinic_id'=>$id_clinic])->all();
		//var_dump($office);die();
        return $this->render('editemployee',[
			'model'=>$model,
			'model2'=>$model2,
			'id' =>$id_clinic,
			'id_user' =>$id_user,
			'office'=>$listoffice,
		]);
    }
	public function actionApprove($id)
    {
		$model = Clinic::findOne($id);
		$data = Clinic::find()->all();
		$model->status_approval =1;
		$model->save(false);
		Yii::$app->getSession()->setFlash('success', '<i class="fa fa-edit"></i> Status Approval berhasil di ubah.');
        return $this->redirect(Url::to(['/clinic']));
    }
	public function actionNonapprove($id)
    {
		$model = Clinic::findOne($id);
		$data = Clinic::find()->all();
		$model->status_approval = Constant::STATUS_NONACTIVE;
		$model->save(false);
		Yii::$app->getSession()->setFlash('success', '<i class="fa fa-edit"></i> Status Approval berhasil di ubah.');
        return $this->redirect(Url::to(['/clinic']));
    }

    public function actionRemove($id){
        Clinic::findOne($id)->delete();
        return json_encode(['status' => 1]);
    }
	
	public function actionCreateemployee($id){
		$model = new User();
		$username = Yii::$app->request->post('User');
        $model->username = $username['email'];
        $model->email = $username['email'];
        $model->password_hash = Yii::$app->getSecurity()->generatePasswordHash('initial');
		//var_dump($model->password_hash);die();
        $model->generateAuthKey();
		$model->role_id = Constant::ROLE_EMPLOYEE;
		$model->status=0;
		$model->created_at=11111;
		$model->updated_at=11111;
		$model->save();
		if($model->save()){
		   $modelmember = new Employee();
		   $member = Yii::$app->request->post('Employee');
		   //var_dump($member);die();
		   $modelmember->name = $member['name'];
		   $modelmember->phone = $member['phone'];
		   $modelmember->office_id = $member['office_id'];
		   $modelmember->user_id = $model->getPrimaryKey();
		   $modelmember->save();
		}else{
			var_dump( $model->errors);
		   die();
		}
		return $this->redirect(['list','id'=>$id]);
	}
	public function actionEditemployee($id,$id_user){
		$em = \common\models\Employee::findOne($id);
		$office = \common\models\Office::findOne($em->office_id);
		$clinic = \common\models\Clinic::find()->where(['id'=>$office->clinic_id])->all();
		foreach($clinic as $c){
			$id_clinic = $c->id;
		}
		
		$model = User::findOne($id_user);
		$username = Yii::$app->request->post('User');
        $model->username = $username['email'];
        $model->email = $username['email'];
        $model->password_hash = Yii::$app->getSecurity()->generatePasswordHash('initial');
		//var_dump($model->password_hash);die();
        $model->generateAuthKey();
		$model->role_id = Constant::ROLE_EMPLOYEE;
		$model->status=0;
		$model->created_at=11111;
		$model->updated_at=11111;
		$model->save();
		if($model->save()){
		   $modelmember = Employee::findOne($id);
		   $member = Yii::$app->request->post('Employee');
		   //var_dump($member);die();
		   $modelmember->name = $member['name'];
		   $modelmember->phone = $member['phone'];
		   $modelmember->office_id = $member['office_id'];
		   $modelmember->user_id = $model->getPrimaryKey();
		   $modelmember->save();
		}else{
			var_dump( $model->errors);
		   die();
		}
		return $this->redirect(['list','id'=>$id_clinic]);
	}
	
	public function actionDeleteemployee($id){
		$em = \common\models\Employee::findOne($id);
		$office = \common\models\Office::findOne($em->office_id);
		$clinic = \common\models\Clinic::find()->where(['id'=>$office->clinic_id])->all();
		foreach($clinic as $c){
			$id_clinic = $c->id;
		}
		
		$model = Employee::findOne($id);
		$user_id = $model->user_id;
        $model->delete();
		User::findOne($user_id)->delete();
        return $this->redirect(['list','id'=>$id_clinic]);
    }
	
	public function actionList($id)
    {
		$data = Office::find()->where(['clinic_id'=>$id])->all();
		//$list_office=array();
		foreach($data as $d){
			$list_office[] = $d['id'];
		}
		//var_dump($list_office);die();
        $searchModel = new \common\models\EmployeeSearch();
        $dataProvider = new \yii\data\ActiveDataProvider([
            'query' => \common\models\Employee::find()->where([
                'office_id' => $list_office
            ])
        ]);
		$employee = \common\models\Employee ::find()->where(['in','office_id',$list_office])->all();
        return $this->render('listemployee',[
			'data'=>$data,
			'employee'=>$employee,
			'id' => $id,
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel
		]);
    }

}

admin/views/clinic/addemployee.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;
use common\models\Constant;
use fedemotta\datatables\DataTables;

$this->title = "Add Employee";
?>

<div class="box box-default">
	<div class="box-header with-border">
		<span class="icon-title"><i class="fa fa-hospital-o"></i></span>
        <h3 class="box-title"><?= $this->title ?></h3>
		<div class="pull-right">
        	<a href="<?=Url::to(['clinic/list','id'=>$id])?>" class="btn btn-default"><i class="fa fa-angle-left"></i> Back</a>
        </div>
    </div>
	<div class="box-body">
		<?php $form = ActiveForm::begin([
				'action' => Url::to(['clinic/createemployee','id'=>$id]),
                'method' => 'POST'
				]); ?>
		<div class="form-group">
			<div class="input-group">
				<span class="input-group-addon" id="basic-addon1"><i class="fa fa-group"></i></span>
				<input type="text" name="Employee[name]" class="form-control" placeholder="Nama" aria-describedby="basic-addon1">
			</div>
		</div>
		<div class="form-group">
			<div class="input-group">
				<span class="input-group-addon" id="basic-addon1"><i class="fa fa-phone"></i></span>
				<input type="text" name="Employee[phone]" class="form-control" placeholder="Telephone" aria-describedby="basic-addon1">
			</div>
		</div>
		<div class="form-group">
			<div class="input-group">
				<span class="input-group-addon" id="basic-addon1"><i class="fa fa-envelope"></i></span>
				<input type="text" name="User[email]" class="form-control" placeholder="Email" aria-describedby="basic-addon1">
			</div>
		</div>
		<div class="form-group">
			<div class="input-group">
				<span class="input-group-addon" id="basic-addon1"><i class="fa fa-building"></i></span>
				<select name="Employee[office_id]" class="form-control" ng-model="form.category_id">
					<?php foreach($office as $o){?>
						<option value="<?=$o['id']?>"><?= $o['name']?> - <?= $o['address']?></option>
					<?php 
						}
					?>
				</select>
			</div>
		</div>
		<div class="form-group">
			<div class="input-group">
				<button type="submit" class="btn btn-primary btn-submit">Simpan</button>	
			</div>
		</div>
		<?php ActiveForm::end(); ?>
	</div>
	<!-- /.box-body -->
</div>

admin/views/clinic/create.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use kartik\file\FileInput;
/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var common\models\search\BeaconSearch $searchModel
 */
$this->title = 'Tambah Data Buku';
?>
<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Data Berita
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Tabel</a></li>
        <li class="active">Data Berita</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Tambah Data Berita</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <?php $form = yii\widgets\ActiveForm::begin([
                'action' => Url::to(['berita/submit']),
                'method' => 'POST',
				'options' => ['enctype' => 'multipart/form-data'],
			 ]);  ?>
			 <div class="box-body">
                <div class="form-group">
                  <label for="namakategori">Judul</label>
                  <?= $form->field($model,'judul')->textInput([
							'class' => 'form-control col-md-7 col-xs-12'
						])->label(false)?>
                </div>
              </div>
			  <div class="box-body">
                <div class="form-group">
                  <label for="namakategori">Description</label>
                  <?= $form->field($model, 'description')->widget(\yii\redactor\widgets\Redactor::className())->label(false) ?>
                </div>
              </div>
				<div class="box-body">
                <div class="form-group">
                  <label for="namakategori">Gambar</label>
                  <?= $form->field($model,'gambar')->fileInput()->label(false);?>
                </div>
              </div>
			  <div class="box-footer">
                <button type="submit" class="btn btn-primary"><i class="fa fa-plus"></i> Tambah</button>
				  <a href="<?= Url::to(["berita/index"]); ?>" type="submit" class="btn btn-danger"><i class="fa fa-times"></i> Cancel</a>
              </div>

			<?php yii\widgets\ActiveForm::end(); ?>
          </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

admin/views/clinic/detail.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use common\models\Constant;
use fedemotta\datatables\DataTables;
$this->title = "Detail Clinic";
?>
 <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Data Clinic
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Tabel</a></li>
        <li class="active">Data Clinic</li>
      </ol>
    </section>
	
	<section class="content">
      <div class="row">
        <div class="col-xs-12">
			<div class="box box-default">
				<div class="box-header with-border">
					<span class="icon-title"><i class="fa fa-hospital-o"></i></span>
					<h3 class="box-title"><?= $this->title ?></h3>
					<div class="pull-right">
						<?= Html::a( "<i class='fa fa-angle-left'></i> Back", ['/clinic'], ['class'=>"btn-back"]) ?>
					</div>
				</div>
				<div class="box-body">
					<div class="row">
						<div class="col-sm-4">
							<div class="row">
								<div class="col-md-12 col-sm-6">
									<div class="detail-klinik__logo"><img class="profile-user-img img-responsive img-circle" src="<?= Yii::getAlias('@uploadsWeb') ?>/<?=  $data->logo ?>" height="100px"></div>
									
								</div>
								<div class="col-md-12 col-sm-6">
									<?php
										if($data['status_approval']==Constant::STATUS_NONACTIVE){
									?>
										<a href="<?=Url::to(['clinic/approve','id'=>$data['id']]);?>" class="btn btn-success btn-block btn-pad">Aktifkan Klinik</a>
									<?php
										}else{
									?>
										<a href="<?=Url::to(['clinic/nonapprove','id'=>$data['id']]);?>" class="btn btn-danger btn-block btn-pad">Nonaktifkan Klinik</a>
									<?php
										}
									?>
									<button data-toggle="modal" data-target="#voucherModal" class="btn btn-default btn-block btn-pad"><i class="fa fa-ticket"></i> Lihat vouchernya</button>
									<div class="border-space-15"></div>
									<br>
									<a id="remove-clinic" href="<?= Url::to(['clinic/remove','id' => $data['id']]) ?>"
									class="btn btn-danger btn-block btn-pad">Hapus Permanen</a>
								</div>
							</div>
						</div>
						<div class="col-sm-8">
							<div class="detail-klinik__name">
								<?=$data['name_clinic']?> 
								<?php
									if($data['status_approval']==Constant::STATUS_NONACTIVE){
										echo '<span class="detail-klinik__status label label-danger">Not Approval</span><br>';
									}else{
										echo '<span class="detail-klinik__status label label-success">Approval</span><br>';
									}
								?>
							</div>
							<div class="detail-klinik__category">
								<strong>Categories</strong> : <?php 
									$code = common\models\CategoryHasClinic::find()->where(['clinic_id'=>$data['id']])->all();
									foreach($code as $co){
										$code1 = common\models\Category::find()->where(['id'=>$co['category_id']])->all();
										foreach($code1 as $c){
											echo '<span class="detail-klinik__status label label-primary">'.$c['name'].'</span> ';
										}
									}
								?>
							</div>
							<div class="detail-klinik__desc">
								<strong>Deskripsi Detail : <br /></strong>
								<?=$data['description']?> 
							</div>
							<div class="detail-klinik__proof">
								<strong>Bukti Izin Menjalankan Klinik : <br /></strong>
								<!--<a href="<?= Yii::getAlias('@uploadsWeb')."/".$data['proof_of_permission'] ?>">Bukti</a>-->
								<button data-toggle="modal" data-target="#buktiModal">Bukti</button>
							</div>				
							<div class="detail-klinik__owner">
								<table>
									<tr>
										<th width="50">Owner</th>
										<td width="10">:</td>
										<td><?=$data['name_contact']?></td>
									</tr>
									<tr>
										<th>Email</th>
										<td>:</td>
										<td><?php 
											$code = common\models\User::find()->where(['id'=>$data['user_id']])->all();
											foreach($code as $co){
												echo $co['email'];
											}
										?></td>
									</tr>
									<tr>
										<th>Phone</th>
										<td>:</td>
										<td><?=$data['phone']?></td>
									</tr>
								</table>
							</div>
							<div class="detail-klinik__office">
								<div class="the-title">Office : </div>
								<ul>
									<?php 
										$code = common\models\Office::find()->where(['clinic_id'=>$data['id']])->all();
										foreach($code as $co){
											$code1 = common\models\City::find()->where(['id'=>$co['city_id']])->all();
											foreach($code1 as $c){
												echo '<li>
														<div class="the-mark"><i class="fa fa-map-marker"></i>
														<span>'.$co['address'].'</span><br>
															<span>'.$c['name'].'</span><br>
														</div>
													<div class="clear"></div>
												</li>';
											}
										}
									?>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>

		</div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

<!-- Modal -->
<div class="modal fade" id="voucherModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">List Voucher</h4>
      </div>
      <div class="modal-body">
	  		<table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
					<th>ID</th>
					<th>Nama</th>
					<th>Harga Voucher</th>
					<th>Expired Date</th>
					<th>Status</th>
					<th>Action</th>
                </tr>
                </thead>
                <tbody>
					<?php 
						$i=1;
						foreach($voucher as $v){
					?>
		            <tr">
		              	<th><?= $i++?></th>
		              	<th><?= $v['name']?></th>
		              	<th class="text-right">Rp. <?= number_format($v['voucher_price'])?></th>
		              	<th class="text-center">
							<?php
								$date = strtotime($v['expire_date']); 
								$check_date = date( 'd-m-Y', $date );
								echo $check_date;
							?> 
						</th>
						<th><?php
							if($v['status']==0){
								echo '<span class="label label-danger">Not Accepted</span>';
							}else{
								echo '<span class="label label-success">Accepted</span>';
							}?></th>
						<th>
						<?php
							if($v['status']==0){?>
						<a href="<?=Url::to(['clinic/accept','id_voucher'=>$v['id']]);?>" type="button" class="btn active btn-warning"><span class="fa fa-edit"></span> Accept</a>
						<?php
							}else{
						?>
						<a href="<?=Url::to(['clinic/nonaccept','id_voucher'=>$v['id']]);?>" type="button" class="btn active btn-danger"><span class="fa fa-edit"></span> Batal Accept</a>
						<?php
							}
						?>
						</th>
		            </tr>
					<?php 
						}
					?>
                </tbody>
              </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="buktiModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Bukti</h4>
      </div>
      <div class="modal-body">
			<img src="<?= Yii::getAlias('@uploadsWeb')."/".$data['proof_of_permission'] ?>" height="300px" width="300px"/>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>