admin/controllers/BankController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\Url;
use common\models\BankAdmin;
use yii\web\UploadedFile;

/**
 * Site controller
 */
class BankController extends Controller {

    /**
     * @var boolean whether to enable CSRF validation for the actions in this controller.
     * CSRF validation is enabled only when both this property and [[Request::enableCsrfValidation]] are true.
     */
    //public $enableCsrfValidation = false;
    
    public function actionIndex() {
		$logo = BankAdmin::find()->all();
	    return $this->render('index', [
			'model' => $logo
		]);
    }
	public function actionEditform($id) {
		$logo = BankAdmin::findOne(['id' => $id]);
		return $this->render('edit', [
			'model' => $logo,
		]);
    }
	public function actionEditform1($id) {
		$logo = BankAdmin::findOne(['id' => $id]);
		return $this->render('edit_gambar', [
			'model' => $logo,
		]);
    }
	public function actionCreate() {
		$logo = new BankAdmin();
		return $this->render('create', [
			'model' => $logo,
		]);
    }
	public function actionEdit($id) {
            $model = $this->findModel($id);
			if (Yii::$app->request->isPost) {
				if ($model->load(Yii::$app->request->post())) {
					$uploadModel = UploadedFile::getInstance($model, 'gambar');
					if ($uploadModel) {
						$namaLogo = $uploadModel->baseName;
						if ($uploadModel->extension == "jpg" || $uploadModel->extension == "jpeg" || $uploadModel->extension == "png") {
							$uploadModel->saveAs('../../frontend/web/berita/' . $namaLogo . '.' . $uploadModel->extension);
							$model->gambar = $namaLogo . '.' . $uploadModel->extension;
						} else {
							return $this->render('index', [
								'model' => $model,
							]);
						}
					}
					
					if ($model->save()) {         
						//var_dump('test');die();
						Yii::$app->getSession()->setFlash('success', '<i class="fa fa-edit"></i> BankAdmin berhasil di ubah.');
						return $this->redirect('index');
					} else {                    
						return $this->render('index', [
									'model' => $model,
						]);
					}
				}
			} else {
				return $this->render('create', [
							'model' => $model,
				]);
			}
            if( !$model->save() ){
               var_dump( $model->errors);
               die();
            }
           return $this->redirect(['index']);
    } 
	public function actionEditgambar($id) {
            $model = $this->findModel($id);
			if (Yii::$app->request->isPost) {
				if ($model->load(Yii::$app->request->post())) {
					$uploadModel = UploadedFile::getInstance($model, 'gambar');
					if ($uploadModel) {
						$namaLogo = $uploadModel->baseName;
						if ($uploadModel->extension == "jpg" || $uploadModel->extension == "jpeg" || $uploadModel->extension == "png") {
							$uploadModel->saveAs('../../frontend/web/berita/' . $namaLogo . '.' . $uploadModel->extension);
							$model->gambar = $namaLogo . '.' . $uploadModel->extension;
						} else {
							return $this->render('index', [
								'model' => $model,
							]);
						}
					}
					
					if ($model->save()) {         
						//var_dump('test');die();
						Yii::$app->getSession()->setFlash('success', '<i class="fa fa-edit"></i> BankAdmin berhasil di ubah.');
						return $this->redirect('index');
					} else {                    
						return $this->render('index', [
									'model' => $model,
						]);
					}
				}
			} else {
				return $this->render('create', [
							'model' => $model,
				]);
			}
            if( !$model->save() ){
               var_dump( $model->errors);
               die();
            }
           return $this->redirect(['index']);
    } 
	public function actionSubmit() {
            $model = new BankAdmin();
			if (Yii::$app->request->isPost) {
				if ($model->load(Yii::$app->request->post())) {
					$uploadModel = UploadedFile::getInstance($model, 'gambar');
					if ($uploadModel) {
						$namaLogo = $uploadModel->baseName;
						if ($uploadModel->extension == "jpg" || $uploadModel->extension == "jpeg" || $uploadModel->extension == "png") {
							$uploadModel->saveAs('../../frontend/web/berita/' . $namaLogo . '.' . $uploadModel->extension);
							$model->gambar = $namaLogo . '.' . $uploadModel->extension;
						} else {
							return $this->render('index', [
								'model' => $model,
							]);
						}
					}
					
					if ($model->save()) {         
						//var_dump('test');die();
						Yii::$app->getSession()->setFlash('success', '<i class="fa fa-save"></i> BankAdmin berhasil di tambahkan.');
						return $this->redirect('index');
					} else {                    
						return $this->render('index', [
									'model' => $model,
						]);
					}
				}
			} else {
				return $this->render('create', [
							'model' => $model,
				]);
			}
            if( !$model->save() ){
               var_dump( $model->errors);
               die();
            }
           return $this->redirect(['index']);
    } 
	public function actionDelete($id)
    {
        $this->findModel($id)->delete();
		Yii::$app->getSession()->setFlash('success', '<i class="fa fa-trash"></i> BankAdmin berhasil di hapus.');
        return $this->redirect(['index']);
    }
	
	protected function findModel($id)
    {
        if (($model = BankAdmin::findOne(['id' => $id])) !== null) {
            return $model;
        } else {
            echo "error";
        }
    }
	
}

admin/controllers/ClinicController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use common\models\Clinic;
use common\models\Employee;
use common\models\ClinicSearch;
use common\models\Constant;
use common\models\Office;
use common\models\Voucher;
use yii\helpers\Url;

/**
 * Site controller
 */
class ClinicController extends Controller
{
    
public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
				'only' => ['index','detail','approve','nonapprove','remove'],
                'rules' => [
                    [
                        'actions' => ['index','detail','approve','nonapprove','remove'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                    'remove' => ['post']
                ],
            ],
        ];
    }    
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new ClinicSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

		$data = Clinic::find()->all();
		return $this->render('index',[
            'search' => $searchModel,
            'provider' => $dataProvider,
			'model' => $data
		]);
    }

    public function actionDetail($id)
    {
		$data = Clinic::findOne($id);

        $searchModel = new \common\models\ClinicSearch();
        $dataProvider = new \yii\data\ActiveDataProvider([
            'query' => \common\models\Voucher::find()->where([
                'clinic_id' => $data->id
            ])
        ]);
		
		$clinic = Clinic::findOne($id);
		$office = Office::find()->where(['clinic_id'=>$clinic['id']])->all();
		$id_office = array();
		foreach($office as $o){
			$id_office[] = $o['id'];
		}
		$listOfVoucher = Voucher::find()->where(['clinic_id' => $clinic->id])->all();
		//var_dump($data);die();
        return $this->render('detail',[
			'data'=>$data,
			'voucher'=>$listOfVoucher,
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel
		]);
    }
	
	public function actionAccept($id_voucher){
		$model = Voucher :: findOne($id_voucher);
		$model->status =1;
		$model->save();
		
		if(!$model->save()){
			var_dump($model->errors);
			die();
		}
		Yii::$app->session->setFlash('success', 'Voucher has been Accepted.');
		return $this->redirect(['clinic/detail','id'=>$model->clinic_id]);
	}
	public function actionNonaccept($id_voucher){
		$model = Voucher :: findOne($id_voucher);
		$model->status =0;
		$model->save();
		
		if(!$model->save()){
			var_dump($model->errors);
			die();
		}
		Yii::$app->session->setFlash('success', 'Voucher has been Accepted.');
		return $this->redirect(['clinic/detail','id'=>$model->clinic_id]);
	}
	public function actionAddemployee($id)
    {
		$model = new \common\models\Employee();
		$office = \common\models\Office::find()->where(['clinic_id'=>$id])->all();
        return $this->render('addemployee',[
			'model'=>$model,
			'id' =>$id,
			'office'=>$office,
		]);
    }
	public function actionUbahemployee($id)
    {
		$model = \common\models\Employee::findOne($id);
		$id_user = $model->user_id;
		$office = \common\models\Office::findOne($model->office_id);
		$clinic = \common\models\Clinic::find()->where(['id'=>$office->clinic_id])->all();
		foreach($clinic as $c){
			$id_clinic = $c->id;
		}
		//var_dump($office);die();
		$model2 = \common\models\User::findOne($id_user);		
		$listoffice = \common\models\Office::find()->where(['clinic_id'=>$id_clinic])->all();
		//var_dump($office);die();
        return $this->render('editemployee',[
			'model'=>$model,
			'model2'=>$model2,
			'id' =>$id_clinic,
			'id_user' =>$id_user,
			'office'=>$listoffice,
		]);
    }
	public function actionApprove($id)
    {
		$model = Clinic::findOne($id);
		$data = Clinic::find()->all();
		$model->status_approval =1;
		$model->save(false);
		Yii::$app->getSession()->setFlash('success', '<i class="fa fa-edit"></i> Status Approval berhasil di ubah.');
        return $this->redirect(Url::to(['/clinic']));
    }
	public function actionNonapprove($id)
    {
		$model = Clinic::findOne($id);
		$data = Clinic::find()->all();
		$model->status_approval = Constant::STATUS_NONACTIVE;
		$model->save(false);
		Yii::$app->getSession()->setFlash('success', '<i class="fa fa-edit"></i> Status Approval berhasil di ubah.');
        return $this->redirect(Url::to(['/clinic']));
    }

    public function actionRemove($id){
        Clinic::findOne($id)->delete();
        return json_encode(['status' => 1]);
    }
	
	public function actionCreateemployee($id){
		$model = new User();
		$username = Yii::$app->request->post('User');
        $model->username = $username['email'];
        $model->email = $username['email'];
        $model->password_hash = Yii::$app->getSecurity()->generatePasswordHash('initial');
		//var_dump($model->password_hash);die();
        $model->generateAuthKey();
		$model->role_id = Constant::ROLE_EMPLOYEE;
		$model->status=0;
		$model->created_at=11111;
		$model->updated_at=11111;
		$model->save();
		if($model->save()){
		   $modelmember = new Employee();
		   $member = Yii::$app->request->post('Employee');
		   //var_dump($member);die();
		   $modelmember->name = $member['name'];
		   $modelmember->phone = $member['phone'];
		   $modelmember->office_id = $member['office_id'];
		   $modelmember->user_id = $model->getPrimaryKey();
		   $modelmember->save();
		}else{
			var_dump( $model->errors);
		   die();
		}
		return $this->redirect(['list','id'=>$id]);
	}
	public function actionEditemployee($id,$id_user){
		$em = \common\models\Employee::findOne($id);
		$office = \common\models\Office::findOne($em->office_id);
		$clinic = \common\models\Clinic::find()->where(['id'=>$office->clinic_id])->all();
		foreach($clinic as $c){
			$id_clinic = $c->id;
		}
		
		$model = User::findOne($id_user);
		$username = Yii::$app->request->post('User');
        $model->username = $username['email'];
        $model->email = $username['email'];
        $model->password_hash = Yii::$app->getSecurity()->generatePasswordHash('initial');
		//var_dump($model->password_hash);die();
        $model->generateAuthKey();
		$model->role_id = Constant::ROLE_EMPLOYEE;
		$model->status=0;
		$model->created_at=11111;
		$model->updated_at=11111;
		$model->save();
		if($model->save()){
		   $modelmember = Employee::findOne($id);
		   $member = Yii::$app->request->post('Employee');
		   //var_dump($member);die();
		   $modelmember->name = $member['name'];
		   $modelmember->phone = $member['phone'];
		   $modelmember->office_id = $member['office_id'];
		   $modelmember->user_id = $model->getPrimaryKey();
		   $modelmember->save();
		}else{
			var_dump( $model->errors);
		   die();
		}
		return $this->redirect(['list','id'=>$id_clinic]);
	}
	
	public function actionDeleteemployee($id){
		$em = \common\models\Employee::findOne($id);
		$office = \common\models\Office::findOne($em->office_id);
		$clinic = \common\models\Clinic::find()->where(['id'=>$office->clinic_id])->all();
		foreach($clinic as $c){
			$id_clinic = $c->id;
		}
		
		$model = Employee::findOne($id);
		$user_id = $model->user_id;
        $model->delete();
		User::findOne($user_id)->delete();
        return $this->redirect(['list','id'=>$id_clinic]);
    }
	
	public function actionList($id)
    {
		$data = Office::find()->where(['clinic_id'=>$id])->all();
		//$list_office=array();
		foreach($data as $d){
			$list_office[] = $d['id'];
		}
		//var_dump($list_office);die();
        $searchModel = new \common\models\EmployeeSearch();
        $dataProvider = new \yii\data\ActiveDataProvider([
            'query' => \common\models\Employee::find()->where([
                'office_id' => $list_office
            ])
        ]);
		$employee = \common\models\Employee ::find()->where(['in','office_id',$list_office])->all();
        return $this->render('listemployee',[
			'data'=>$data,
			'employee'=>$employee,
			'id' => $id,
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel
		]);
    }

}

admin/views/layouts/main.php
<?php

//$segments = explode('/', trim(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH), '/'));

/* @var $this \yii\web\View */
/* @var $content string */

use backend\assets\AppAsset;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use yii\helpers\Url;

AppAsset::register($this);

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title>Berobat</title>
    <?php $this->head() ?>

</head>
<body class="hold-transition skin-green layout-boxed sidebar-mini">
<?php $this->beginBody() ?>
   <div class="wrapper">

  <header class="main-header">
    <!-- Logo -->
    <a href="index2.html" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>B</b>B</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Berobat</b></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="<?= Url::to(['site/logout'])?>" data-method="post">
			  <span class="fa fa-sign-out"> Logout</span>
            </a>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="<?= Yii::$app->urlManager->createUrl(["/templates/dist/img/user8-128x128.jpg"]); ?>" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>Admin</p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>
      
      <!-- sidebar menu: : style can be found in sidebar.less -->
	  
      <ul class="sidebar-menu">
        <li class="header">MAIN NAVIGATION</li>
		<?php if(Yii::$app->controller->id == 'site'  && Yii::$app->controller->action->id == 'index'){?>
			<li class="active"><a href="<?= Url::to(['site/index'])?>"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a></li>
		<?php }else{ ?>
			<li><a href="<?= Url::to(['site/index'])?>"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a></li>
		<?php } ?>
		
		<li><a href="<?= Url::to(['clinic/index'])?>"><i class="fa fa-database"></i> <span>Data Clinic</span></a></li>
		<li><a href="<?= Url::to(['member/index'])?>"><i class="fa fa-database"></i> <span>Data Member</span></a></li>
		<li><a href="<?= Url::to(['voucher/index'])?>"><i class="fa fa-database"></i> <span>Data Voucher</span></a></li>
		<li><a href="<?= Url::to(['bank/index'])?>"><i class="fa fa-database"></i> <span>Data Bank Admin</span></a></li>
		<li><a href="<?= Url::to(['kategoriclinic/index'])?>"><i class="fa fa-database"></i> <span>Data Kategori Clinic</span></a></li>
		
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

        <?= $content; ?>

	<footer class="main-footer">
		<div class="pull-right hidden-xs">
		  <b>Version</b> 2.3.7
		</div>
		<strong>Copyright &copy; 2014-2016 <a href="http://almsaeedstudio.com">Almsaeed Studio</a>.Admin LTE</strong> All rights
		reserved.
	  </footer>

	</div>
<?php $this->endBody() ?>
    <!-- this page specific inline scripts -->
	
		<script>
	  $(function () {
		$("#example1").DataTable();
		$('#example2').DataTable({
		  "paging": true,
		  "lengthChange": false,
		  "searching": false,
		  "ordering": true,
		  "info": true,
		  "autoWidth": false
		});
	  });
	  $(function(){
			$(".datepicker").datepicker({
				dateFormat:"yy-mm-dd"
			});
			$(".datepicker2").datepicker({
				dateFormat:"yy-mm-dd"
			});
			$(".datepicker3").datepicker({
				dateFormat:"yy-mm-dd"
			});
		});
	</script>
</body>
</html>
<?php $this->endPage() ?>

admin/views/layouts/main2.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use backend\assets\AppAsset;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'My Company',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems = [
        ['label' => 'Home', 'url' => ['/site/index']],
    ];
    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
    } else {
        $menuItems[] = '<li>'
            . Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                'Logout (' . Yii::$app->user->identity->username . ')',
                ['class' => 'btn btn-link logout']
            )
            . Html::endForm()
            . '</li>';
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

admin/views/layouts/main_login.php
<?php

//$segments = explode('/', trim(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH), '/'));

/* @var $this \yii\web\View */
/* @var $content string */

use backend\assets\LoginAsset;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;

LoginAsset::register($this);
dmstr\web\AdminLteAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" ng-app="app">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>

<body class="login-page">

<?php $this->beginBody() ?>

    <?= $content ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>